# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-29 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail',
            field=models.TextField(default='', verbose_name='\u8bfe\u7a0b\u8be6\u60c5'),
        ),
    ]
