# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-17 13:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 13, 28, 28, 763668), verbose_name='\u53d1\u9001\u65f6\u95f4'),
        ),
    ]
